import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import { Inter } from "next/font/google";
import "./globals.css";


const inter =  Inter({
  subsets: ["latin"],

});

export const metadata: Metadata = {
  title: "Google Docs",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body suppressHydrationWarning
        className={inter.className}
      >
        {children}
      </body>
    </html>
  );
}
